version: '3'
services:
  system:
    build: .
    image: "koudou"
    container_name: "koudou"
    ports:
      - "3030:3030"
    links:
      - nodered
  nodered:
    image: nodered
    build: ./nodered-local
    ports:
      - "9000:9000"